apiVersion: authorization.openshift.io/v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  name: grafana-custom
roleRef:
  name: grafana
subjects:
- kind: ServiceAccount
  name: grafana-custom
  namespace: grafana
userNames:
- system:serviceaccount:grafana:grafana-custom
